version: '2'
services:
    ducarmolocacoes-app:
        image: ducarmolocacoes
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ducarmolocacoes-mysql:3306/ducarmolocacoes?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://ducarmolocacoes-elasticsearch:9200
        ports:
            - 8080:8080
    ducarmolocacoes-mysql:
        extends:
            file: mysql.yml
            service: ducarmolocacoes-mysql
    ducarmolocacoes-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ducarmolocacoes-elasticsearch
